version: '2'

services:
    influxdb:
        image: influxdb:1.0
        restart: always
        ports: 
            - 8083:8083
            - 8086:8086
        volumes:
            - $PWD/influxdb:/var/lib/influxdb
            - $PWD/influx.toml:/etc/influx.toml
        entrypoint:
            - influxd
            - --config 
            - /etc/influx.toml

    telegraf:
        image: telegraf:1.0
        restart: always
        ports:
            - 8125:8125/udp
        volumes:
            - $PWD/telegraf.conf:/etc/telegraf/telegraf.conf:ro

    chronograf:
        image: chronograf:1.0.0-rc1
        restart: always
        links:
            - influxdb
        volumes:
            - $PWD/chronograf:/var/lib/chronograf
        ports: 
            - 10000:10000

    kapacitor:
        image: kapacitor:1.0
        restart: always
        links:
            - influxdb
        ports:
            - 9092:9092
        volumes:
            - $PWD/kapacitor:/var/lib/kapacitor
            - ~/tasks:/tasks
            - $PWD/kapacitor.conf:/etc/kapacitor/kapacitor.conf:ro
        environment:
            - INFLUXDB_URL=http://influxdb:8086
            - INFLUXDB_DB=telegraf  
